spring.application.name=employeeApp
spring.datasource.url=jdbc:postgresql://localhost:5432/company_employee
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#Enable Simple Cache
#spring.cache.type=simple

#Enable Redis Cache
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379